version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
        - mysql-data:/var/lib/mysql  
    ports:
      - "4306:3306"

  web:
    build: .
    command: bundle exec unicorn -p 3000 -c config/unicorn.rb
    volumes:
      - .:/stage
    ports:
      - "3000:3000"
    links:
      - db
volumes:
  mysql-data:
  bundle: 